import type { INodeProperties } from 'n8n-workflow';
import { dateRangeFields, filtersField, siteSelect } from '../../shared/descriptions';
import { checkApiError, buildQueryBody, simplifyQueryResponse } from '../../shared/request';

const showOnlyForReport = {
	resource: ['report'],
};

const breakdownOnly = {
	resource: ['report'],
	dimension: [
		'event:folder',
		'event:goal',
		'event:hostname',
		'event:name',
		'event:page',
		'event:props',
		'event:status_code',
		'visit:browser',
		'visit:browser_version',
		'visit:channel',
		'visit:city',
		'visit:country',
		'visit:device',
		'visit:entry_page',
		'visit:exit_page',
		'visit:os',
		'visit:os_version',
		'visit:referrer',
		'visit:region',
		'visit:source',
		'visit:utm_campaign',
		'visit:utm_content',
		'visit:utm_medium',
		'visit:utm_source',
		'visit:utm_term',
	],
};

export const reportDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: showOnlyForReport },
		options: [
			{
				name: 'Query',
				value: 'query',
				action: 'Query analytics',
				description:
					'Get totals, a time series or a ranked breakdown of visitors, pageviews and other metrics',
				routing: {
					request: {
						method: 'POST',
						url: '/query',
					},
					send: {
						preSend: [buildQueryBody],
					},
					output: {
						postReceive: [checkApiError, simplifyQueryResponse],
					},
				},
			},
		],
		default: 'query',
	},
	{
		...siteSelect,
		displayOptions: { show: showOnlyForReport },
	},
	{
		displayName: 'Metrics',
		name: 'metrics',
		type: 'multiOptions',
		required: true,
		displayOptions: { show: showOnlyForReport },
		options: [
			{ name: 'Bounce Rate', value: 'bounce_rate' },
			{ name: 'Conversion Rate', value: 'conversion_rate', description: 'Goal breakdown only' },
			{ name: 'Engagement Time', value: 'engagement_time' },
			{ name: 'Events', value: 'events', description: 'Breakdowns only' },
			{ name: 'Exit Rate', value: 'exit_rate', description: 'Exit page breakdown only' },
			{ name: 'Pageviews', value: 'pageviews' },
			{ name: 'Scroll Depth', value: 'scroll_depth', description: 'Breakdowns only' },
			{ name: 'Time on Page', value: 'time_on_page', description: 'Breakdowns only' },
			{ name: 'Views per Visit', value: 'views_per_visit' },
			{ name: 'Visit Duration', value: 'visit_duration' },
			{ name: 'Visitors', value: 'visitors' },
			{ name: 'Visits', value: 'visits' },
		],
		default: ['visitors', 'pageviews'],
		description:
			'Each breakdown computes only some metrics. See https://statable.com/docs/developers/stats-api/query/#breakdowns.',
	},
	...dateRangeFields(showOnlyForReport),
	{
		displayName: 'Group By',
		name: 'dimension',
		type: 'options',
		displayOptions: { show: showOnlyForReport },
		options: [
			{ name: 'Browser', value: 'visit:browser' },
			{ name: 'Browser Version', value: 'visit:browser_version' },
			{ name: 'Channel', value: 'visit:channel' },
			{ name: 'City', value: 'visit:city' },
			{ name: 'Country', value: 'visit:country' },
			{ name: 'Custom Event', value: 'event:name' },
			{ name: 'Custom Property', value: 'event:props' },
			{ name: 'Day', value: 'time:day' },
			{ name: 'Device', value: 'visit:device' },
			{ name: 'Entry Page', value: 'visit:entry_page' },
			{ name: 'Exit Page', value: 'visit:exit_page' },
			{ name: 'Folder', value: 'event:folder' },
			{ name: 'Goal', value: 'event:goal' },
			{ name: 'Hostname', value: 'event:hostname' },
			{ name: 'Hour', value: 'time:hour' },
			{ name: 'Minute (Realtime Only)', value: 'time:minute' },
			{ name: 'Month', value: 'time:month' },
			{ name: 'Nothing (Totals)', value: 'none' },
			{ name: 'OS', value: 'visit:os' },
			{ name: 'OS Version', value: 'visit:os_version' },
			{ name: 'Page', value: 'event:page' },
			{ name: 'Referrer', value: 'visit:referrer' },
			{ name: 'Region', value: 'visit:region' },
			{ name: 'Source', value: 'visit:source' },
			{ name: 'Status Code', value: 'event:status_code' },
			{ name: 'UTM Campaign', value: 'visit:utm_campaign' },
			{ name: 'UTM Content', value: 'visit:utm_content' },
			{ name: 'UTM Medium', value: 'visit:utm_medium' },
			{ name: 'UTM Source', value: 'visit:utm_source' },
			{ name: 'UTM Term', value: 'visit:utm_term' },
			{ name: 'Week', value: 'time:week' },
		],
		default: 'none',
		description:
			'Nothing returns totals, a time unit returns a series, anything else returns a ranked breakdown',
	},
	{
		displayName: 'Property Key',
		name: 'propertyKey',
		type: 'string',
		required: true,
		displayOptions: { show: { ...showOnlyForReport, dimension: ['event:props'] } },
		default: '',
		placeholder: 'e.g. plan',
		description:
			'Custom property to rank. Needs a filter on the event field naming the event that carries it. Use Property → Get Many to discover keys.',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		displayOptions: { show: breakdownOnly },
		typeOptions: { minValue: 1, maxValue: 1000 },
		default: 50,
		description: 'Max number of results to return',
	},
	{
		displayName: 'Offset',
		name: 'offset',
		type: 'number',
		displayOptions: { show: breakdownOnly },
		typeOptions: { minValue: 0 },
		default: 0,
		description: 'Number of rows to skip, for paging through a breakdown',
	},
	{
		displayName: 'Compare to Previous Period',
		name: 'compare',
		type: 'boolean',
		displayOptions: { show: showOnlyForReport },
		default: false,
		description:
			'Whether to add the previous value and percent change for the equal window right before the date range',
	},
	filtersField(showOnlyForReport, 'Narrow the query. Multiple filters are combined with AND.'),
	{
		displayName: 'Simplify',
		name: 'simplify',
		type: 'boolean',
		displayOptions: { show: showOnlyForReport },
		default: true,
		description:
			'Whether to return one flat item per row instead of the raw response with query echo and paging meta',
	},
];
